<?php

namespace App\Filament\Resources;

use App\Filament\Resources\AboutUsPageResource\Pages;
use App\Filament\Resources\AboutUsPageResource\RelationManagers;
use App\Models\AboutUs;
use App\Tables\Columns\SpatieImage;
use App\Traits\BranchTrait;
use Filament\Forms;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Textarea;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Filament\Tables\Columns\Column;
use Filament\Tables\Columns\ImageColumn;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use Spatie\MediaLibrary\Support\MediaLibraryPro;

class AboutUsPageResource extends Resource
{
    use BranchTrait;
    
    protected static ?string $model = AboutUs::class;
    protected static ?string $pluralLabel = 'О нас';
    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Card::make()
                    ->schema([
                        SpatieMediaLibraryFileUpload::make('main_image')->image()->collection('main_image')->label('Главная картинка')->maxSize(10240),
                        SpatieMediaLibraryFileUpload::make('second_image')->image()->collection('second_image')->label('№2 картинка')->maxSize(10240),
                        SpatieMediaLibraryFileUpload::make('third_image')->image()->collection('third_image')->label('№3 картинка')->maxSize(10240),
                        SpatieMediaLibraryFileUpload::make('fourth_image')->image()->collection('fourth_image')->label('№4 картинка')->maxSize(10240),
                    ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                SpatieImage::make('main_image')->label('Главная картинка'),
                SpatieImage::make('second_image')->label('№2 картинка'),
                SpatieImage::make('third_image')->label('№3 картинка'),
                SpatieImage::make('fourth_image')->label('№4 картинка'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }
    public static function canDelete(Model $record): bool
    {
        return false; // TODO: Change the autogenerated stub
    }
    public static function canCreate(): bool
    {
        return false; // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListAboutUsPage::route('/'),
            'create' => Pages\CreateAboutUsPage::route('/create'),
            'edit' => Pages\EditAboutUsPage::route('/{record}/edit'),
        ];
    }
}
