<?php

namespace App\Filament\Resources;

use App\Filament\Resources\OfertaResource\Pages;
use App\Filament\Resources\OfertaResource\RelationManagers;
use App\Models\Oferta;
use Faker\Provider\Text;
use Filament\Forms;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class OfertaResource extends Resource
{
    protected static ?string $model = Oferta::class;

    protected static ?string $navigationLabel = 'Оферта';
    protected static ?string $breadcrumb = 'Оферта';
    protected static ?string $label = 'Оферта';
    protected static ?string $pluralLabel = 'Оферта';

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
                Forms\Components\Card::make()
                    ->schema([
                Forms\Components\TextInput::make('title')->label('Заголовок'),
                Forms\Components\RichEditor::make('oferta')->label('Оферта')
                        ]),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                //
                Tables\Columns\TextColumn::make('title')->label('Заголовок')->limit(50),
                Tables\Columns\TextColumn::make('oferta')->label('Оферта')->limit(50)
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

//    public static function canDelete(Model $record): bool
//    {
//        return false; // TODO: Change the autogenerated stub
//    }
//
//    public static function canCreate(): bool
//    {
//        return false; // TODO: Change the autogenerated stub
//    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListOfertas::route('/'),
            'create' => Pages\CreateOferta::route('/create'),
            'edit' => Pages\EditOferta::route('/{record}/edit'),
        ];
    }
}
